version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: scrum_board_full_
      POSTGRES_PASSWORD: "_TOFLjgUoQyWdA2dGaD9x4Z6Ent6-d0c"
    volumes:
      - scrum_board_full__data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "FcAwgpmqLAJBrZ6Ln2RK8pHmK2HF6WSB"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  scrum_board_full__data:
